<a href="https://colab.research.google.com/github/Jeong-Yunmi/pytorch-tutorial/blob/main/Lap_08_1_Perceptron.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [3]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'

torch.manual_seed(777)
if device == 'cuda':
  torch.cuda.manual_seed_all(777)

In [4]:
X = torch.FloatTensor([[0, 0], [0, 1], [1, 0], [1, 1]]).to(device)
Y = torch.FloatTensor([[0], [1], [1], [0]]).to(device)

In [6]:
def train(model, optimizer, criterion):
    for step in range(10001):
        hypothesis = model(X)

        cost = criterion(hypothesis, Y)

        optimizer.zero_grad()
        cost.backward()
        optimizer.step()

        if step % 1000 == 0:
            print(f'Step : {step}, Cost : {cost.item():.6f}')

In [7]:
def compute_accuracy(model, X, Y):
    with torch.no_grad():
        hypothesis = model(X)
        predicted = (hypothesis > 0.5).float()
        accuracy = (predicted == Y).float().mean()
        print(
            'Hypothesis:\n', hypothesis.detach().cpu().numpy(), 
            '\nPredict:\n', predicted.detach().cpu().numpy(),
            '\nGround Truth:\n', Y.cpu().numpy(),
            '\nAccuracy:\n', accuracy.item()
            )

In [9]:
linear = torch.nn.Linear(2, 1, bias=True)
sigmoid = torch.nn.Sigmoid()

model = torch.nn.Sequential(linear, sigmoid).to(device)

criterion = torch.nn.BCELoss().to(device)
optimizer = torch.optim.SGD(model.parameters(), lr=1)

In [10]:
train(model, optimizer, criterion)

Step : 0, Cost : 0.766642
Step : 1000, Cost : 0.693147
Step : 2000, Cost : 0.693147
Step : 3000, Cost : 0.693147
Step : 4000, Cost : 0.693147
Step : 5000, Cost : 0.693147
Step : 6000, Cost : 0.693147
Step : 7000, Cost : 0.693147
Step : 8000, Cost : 0.693147
Step : 9000, Cost : 0.693147
Step : 10000, Cost : 0.693147


In [11]:
compute_accuracy(model, X, Y)

Hypothesis:
 [[0.5]
 [0.5]
 [0.5]
 [0.5]] 
Predict:
 [[0.]
 [0.]
 [0.]
 [0.]] 
Ground Truth:
 [[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
 0.5


In [12]:
linear1 = torch.nn.Linear(2, 2, bias=True)
linear2 = torch.nn.Linear(2, 1, bias=True)
sigmoid = torch.nn.Sigmoid()

model2 = torch.nn.Sequential(linear1, sigmoid, linear2, sigmoid).to(device)

criterion = torch.nn.BCELoss().to(device)
optimizer = torch.optim.SGD(model2.parameters(), lr=1)

In [13]:
train(model2, optimizer, criterion)

Step : 0, Cost : 0.696631
Step : 1000, Cost : 0.693132
Step : 2000, Cost : 0.692953
Step : 3000, Cost : 0.101294
Step : 4000, Cost : 0.015544
Step : 5000, Cost : 0.008253
Step : 6000, Cost : 0.005600
Step : 7000, Cost : 0.004233
Step : 8000, Cost : 0.003401
Step : 9000, Cost : 0.002841
Step : 10000, Cost : 0.002439


In [14]:
compute_accuracy(model2, X, Y)

Hypothesis:
 [[0.00212983]
 [0.99716175]
 [0.9971456 ]
 [0.00192105]] 
Predict:
 [[0.]
 [1.]
 [1.]
 [0.]] 
Ground Truth:
 [[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
 1.0


In [16]:
linear1 = torch.nn.Linear(2, 10, bias=True)
linear2 = torch.nn.Linear(10, 10, bias=True)
linear3 = torch.nn.Linear(10, 10, bias=True)
linear4 = torch.nn.Linear(10, 1, bias=True)
sigmoid = torch.nn.Sigmoid()

model3 = torch.nn.Sequential(linear1, sigmoid, linear2, sigmoid, linear3, sigmoid, linear4, sigmoid).to(device)

criterion = torch.nn.BCELoss().to(device)
optimizer = torch.optim.SGD(model3.parameters(), lr=1)

In [18]:
train(model3, optimizer, criterion)

Step : 0, Cost : 0.000141
Step : 1000, Cost : 0.000118
Step : 2000, Cost : 0.000101
Step : 3000, Cost : 0.000088
Step : 4000, Cost : 0.000079
Step : 5000, Cost : 0.000071
Step : 6000, Cost : 0.000064
Step : 7000, Cost : 0.000059
Step : 8000, Cost : 0.000054
Step : 9000, Cost : 0.000050
Step : 10000, Cost : 0.000047


In [19]:
compute_accuracy(model, X, Y)

Hypothesis:
 [[0.5]
 [0.5]
 [0.5]
 [0.5]] 
Predict:
 [[0.]
 [0.]
 [0.]
 [0.]] 
Ground Truth:
 [[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
 0.5
